#!/bin/bash

rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out randomtestadventurer testDrawCard testDrawCard.exe badTestDrawCard

gcc -c rngs.c -g  -Wall -fpic -coverage -lm -std=c99

gcc -c dominion.c -g  -Wall -fpic -coverage -lm -std=c99

gcc -o playdom playdom.c -g dominion.o rngs.o -Wall -fpic -coverage -lm -std=c99

gcc -c interface.c -g  -Wall -fpic -coverage -lm -std=c99

gcc -o randomtestadventurer -g randomtestadventurer.c dominion.o rngs.o -Wall -fpic -coverage -lm -std=c99

gcc -o player player.c -g  dominion.o rngs.o interface.o -Wall -fpic -coverage -lm -std=c99




